version: "3.1"

services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
  db-interface:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./jovem-aprendiz-bot:/app
    env_file:
      - ./jovem-aprendiz-bot/conf/.env
    entrypoint: python ./telegram.py
    links:
      - db
    depends_on:
      - db
